// GENERATED by engine/sync.mjs from the app's template-linkages.ts.
// Do not edit: re-run `node engine/sync.mjs` instead.
import { APP } from './links'

/** Each card's "open this one" address: the template's own URL payload. */
export const TEMPLATE = {
  fourBar: `${APP}/?2P.Fe,1E8.A,0.1011.6A,A,0mv,0VU,0.0B,B,0e_,E6,0.0C,C,l1,WW,0.4D,D,qD,0Pk,0..YRAB,AB,0,0,0ix,08i,303e9f,A,B,,.YRBC,BC,0,0,32,NJ,26A69A,B,C,,.YRCD,CD,0,0,nd,3P,0d125a,C,D,,...N_p`,
  slider: `${APP}/?2P.Fe,1E8.A,0.1011.6A,A,0mA,0c,0.0B,B,0Yt,bK,0.0C,C,il,H-,0.5D,D,il,H-,0..YRAB,AB,0,0,0fW,IN,303e9f,A,B,,.YRBC,BC,0,0,4y,Rf,26A69A,B,C,,.YPCD,CD,0,0,0,0,,C,D,,...N_e`,
  flywheel: `${APP}/?2P.Ay,1E8.5,0.1011.6A,A,0,0,0,,,,2SG.0B,B,Fe,0,0.0R,R,0Lu,0,0.0C,C,17u,0,0.5P,P,17u,0,0..0RABR,Flywheel,0,0,025,0,303e9f,A,B,R,,.YRBC,Connecting rod,0,0,hm,0,26A69A,B,C,,.YPCP,CP,0,0,0,0,,C,P,,...N_C`,
  yoke: `${APP}/?2P.Ay,1E8.A,0.1011.6A,A,0,0,0.0B,B,Fe,0,0.8C,C,Fe,0VG,0.0D,D,Fe,S8,0.1E,E,Fe,0,0,CD,C,D.5F,F,Fe,0VG,0..YRAB,AB,0,0,7q,0,303e9f,A,B,,.YRCD,CD,0,0,Fe,01a,26A69A,C,D,,.YPBE,BE,0,0,0,0,,B,E,,.YPCF,CF,0,0,0,0,,C,F,,...N_T`,
  cylinderBoom: `${APP}/?2P.Ay,Fe.5,0.1011.4O,O,0,0,0.0C,C,0,_W,0.4G,G,ku,0,0.0N,N,Ju,Z-,0.8P,P,R0,QX,0.ZS,S,R0,QX,0,GN,G,N..YROC,OC,0,0,0,VG,303e9f,O,C,,.YRGN,GN,0,0,XO,I0,0d125a,G,N,,.YRPC,PC,0,0,DW,iW,26A69A,P,C,,.YPPS,PS,0,0,0,0,,P,S,,...N_X`,
  whitworth: `${APP}/?2P.Ay,1E8.A,0.1011.6A,A,0,0,0.0B,B,0,ku,0.4C,C,Fe,0,0.0D,D,095,1A7,0.1P,P,0,ku,0,CD,C,D..YRAB,AB,0,0,0,NS,303e9f,A,B,,.YRCD,CD,0,0,3H,b4,0d125a,C,D,,.YPBP,BP,0,0,0,0,,B,P,,...N_r`,
  shaper: `${APP}/?2P.Ay,1E8.A,0.1011.6A,A,0,0,0.0B,B,Fe,0,0.4C,C,0,0ku,0.0D,D,Oj,RF,0.0R,R,qW,si,0.1P,P,Fe,0,0,CD,C,D.5Q,Q,qW,si,0..YRAB,AB,0,0,7q,0,303e9f,A,B,,.YRCD,CD,0,0,CN,09q,0d125a,C,D,,.YRDR,DR,0,0,cd,e_,26A69A,D,R,,.YPBP,BP,0,0,0,0,,B,P,,.YPRQ,RQ,0,0,0,0,,R,Q,,...N_9`,
  stephenson: `${APP}/?2P.Fe,1E8.A,0.1011.6A,A,0YP,0ce,0.0B,B,0cQ,0FI,0.0C,C,lC,1-,0.4D,D,ow,0U1,0.0E,E,033,D-,0.0F,F,Dc,nj,0.4G,G,1M0,GJ,0..YRAB,AB,0,0,0aP,0Qz,303e9f,A,B,,.YRBCE,BCE,0,0,1w,E,26A69A,B,C,E,,.YRCD,CD,0,0,n3,0E1,0d125a,C,D,,.YREF,EF,0,0,5H,Vs,00695C,E,F,,.YRFG,FG,0,0,np,X0,303e9f,F,G,,...N_Z`,
  watt: `${APP}/?2P.Fe,1E8.A,0.1011.6A,A,0Qh,0Kn,0.0B,B,0e1,9i,0.0C,C,bT,LF,0.0D,D,0G5,tZ,0.0E,E,V5,1_z,0.0F,F,1mM,1Gv,0.4G,G,1rt,0ey,0..YRAB,AB,0,0,0XM,05Z,303e9f,A,B,,.YRBCD,BCD,0,0,06D,Sr,26A69A,B,C,D,,.YRDE,DE,0,0,7W,1RG,00695C,D,E,,.YREF,EF,0,0,17j,1dx,26A69A,E,F,,.YRFCG,FCG,0,0,1PE,KQ,0d125a,F,C,G,,...N_k`,
  dragLink: `${APP}/?2P.Ay,1E8.A,0.1011.6A,A,0,0,0.0B,B,0,YO,0.0C,C,cU,LL,0.4D,D,Fe,0,0..YRAB,AB,0,0,0,HC,303e9f,A,B,,.YRBC,BC,0,0,JF,Rs,26A69A,B,C,,.YRCD,CD,0,0,R3,Ag,0d125a,C,D,,...N_e`,
  jansen: `${APP}/?2P.1jO,1E8.8,0.1011.6O,O,0,0,0.0A,A,3gO,0,0.4G,G,09Hm,01vu,0.0B,B,05tE,7ee,0.0C,C,0IGg,1-F,0.0D,D,06b8,0B7B,0.0E,E,0ETW,06sL,0.GF,F,0AYO,0MPj,0..YROA,OA,0,0,1rC,0,303e9f,O,A,,.YRAB,AB,0,0,016R,3qK,26A69A,A,B,,.YRGBC,GBC,0,0,0B8Z,2ag,0d125a,G,B,C,,.YRAD,AD,0,0,01TO,05Zc,00695C,A,D,,.YRGD,GD,0,0,07xS,06WY,303e9f,G,D,,.YRCE,CE,0,0,0GN5,02RZ,B2DFDB,C,E,,.YRDEF,DEF,0,0,0AXh,0DT4,26A69A,D,E,F,,...N_O`,
} as const
