// GENERATED by engine/sync.mjs from the app's template-linkages.ts.
// Do not edit: re-run `node engine/sync.mjs` instead.
import { APP } from './links'

/** Each card's "open this one" address: the template's own URL payload. */
export const TEMPLATE = {
  fourBar: `${APP}/?2P.Fe,1E8.A,0.1011.6A,A,0mv,0VU,0.0B,B,0e_,E6,0.0C,C,l1,WW,0.4D,D,qD,0Pk,0..YRAB,AB,0,0,0ix,08i,303e9f,A,B,,.YRBC,BC,0,0,32,NJ,26A69A,B,C,,.YRCD,CD,0,0,nd,3P,0d125a,C,D,,...N_p`,
  slider: `${APP}/?2P.Fe,1E8.A,0.1011.6A,A,0mA,0c,0.0B,B,0Yt,bK,0.0C,C,il,H-,0.5D,D,il,H-,0..YRAB,AB,0,0,0fW,IN,303e9f,A,B,,.YRBC,BC,0,0,4y,Rf,26A69A,B,C,,.YPCD,CD,0,0,0,0,,C,D,,...N_e`,
  flywheel: `${APP}/?2P.Ay,1E8.5,0.1011.6A,A,0,0,0,,,,2SG.0B,B,Fe,0,0.0R,R,0Lu,0,0.0C,C,17u,0,0.5P,P,17u,0,0..0RABR,Flywheel,0,0,025,0,303e9f,A,B,R,,.YRBC,Connecting rod,0,0,hm,0,26A69A,B,C,,.YPCP,CP,0,0,0,0,,C,P,,...N_C`,
  yoke: `${APP}/?2P.Ay,1E8.A,0.1011.6A,A,0,0,0.0B,B,Fe,0,0.8C,C,Fe,0VG,0.0D,D,Fe,S8,0.1E,E,Fe,0,0,CD,C,D.5F,F,Fe,0VG,0..YRAB,AB,0,0,7q,0,303e9f,A,B,,.YRCD,CD,0,0,Fe,01a,26A69A,C,D,,.YPBE,BE,0,0,0,0,,B,E,,.YPCF,CF,0,0,0,0,,C,F,,...N_T`,
  cylinderBoom: `${APP}/?2P.Ay,Fe.5,0.1011.4O,O,0,0,0.0C,C,0,_W,0.4G,G,ku,0,0.0N,N,Ju,Z-,0.8P,P,R0,QX,0.ZS,S,R0,QX,0,GN,G,N..YROC,OC,0,0,0,VG,303e9f,O,C,,.YRGN,GN,0,0,XO,I0,0d125a,G,N,,.YRPC,PC,0,0,DW,iW,26A69A,P,C,,.YPPS,PS,0,0,0,0,,P,S,,...N_X`,
} as const
